### ISSUE TITLE
Selenium support for PhantomJS has been deprecated

### ISSUE THREAD

**Issue by novmikvis** [derrrr/vk-ablum-downloader#1]
I am having trouble running the script

```
 UserWarning: Selenium support for PhantomJS has been deprecated, please use headless versions of Chrome or Firefox instead
  warnings.warn('Selenium support for PhantomJS has been deprecated, please use headless '
Traceback (most recent call last):
  File "vk_album.py", line 217, in <module>
    main()
  File "vk_album.py", line 197, in main
    album = album_process(args[0], args[2])
  File "vk_album.py", line 71, in __init__
    self.driver = webdriver.PhantomJS(PhantomJS_path)
  File "C:\Python36\lib\site-packages\selenium\webdriver\phantomjs\webdriver.py", line 56, in __init__
    self.service.start()
  File "C:\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 98, in start
    self.assert_process_still_running()
  File "C:\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service .../vk-album-dl/phantomjs/bin/phantomjs.exe unexpectedly exited.
```

**Comment by teambug2000** [comment]
> I am having trouble running the script
> 
> ```
>  UserWarning: Selenium support for PhantomJS has been deprecated, please use headless versions of Chrome or Firefox instead
>   warnings.warn('Selenium support for PhantomJS has been deprecated, please use headless '
> Traceback (most recent call last):
>   File "vk_album.py", line 217, in <module>
>     main()
>   File "vk_album.py", line 197, in main
>     album = album_process(args[0], args[2])
>   File "vk_album.py", line 71, in __init__
>     self.driver = webdriver.PhantomJS(PhantomJS_path)
>   File "C:\Python36\lib\site-packages\selenium\webdriver\phantomjs\webdriver.py", line 56, in __init__
>     self.service.start()
>   File "C:\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 98, in start
>     self.assert_process_still_running()
>   File "C:\Python36\lib\site-packages\selenium\webdriver\common\service.py", line 111, in assert_process_still_running
>     % (self.path, return_code)
> selenium.common.exceptions.WebDriverException: Message: Service .../vk-album-dl/phantomjs/bin/phantomjs.exe unexpectedly exited.
> ```

i have the same !
